application: cloudlock-potamus
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

builtins:
- appstats: on

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
- url: /static
  static_dir: static
- url: /static/img
  static_dir: static/img
- url: /static/js
  static_dir: static/js
- url: .*
  script: main.app
